# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/AddBall.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddObject(object):
    def setupUi(self, AddObject):
        AddObject.setObjectName("AddObject")
        AddObject.resize(467, 416)
        AddObject.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(AddObject)
        self.centralwidget.setObjectName("centralwidget")

        self.mass_label = QtWidgets.QLabel(self.centralwidget)
        self.mass_label.setGeometry(QtCore.QRect(30, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mass_label.setFont(font)

        self.velocity_label = QtWidgets.QLabel(self.centralwidget)
        self.velocity_label.setGeometry(QtCore.QRect(30, 234, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.velocity_label.setFont(font)

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 274, 401, 111))

        self.tab = QtWidgets.QWidget()

        self.x_label = QtWidgets.QLabel(self.tab)
        self.x_label.setGeometry(QtCore.QRect(18, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x_label.setFont(font)

        self.y_label = QtWidgets.QLabel(self.tab)
        self.y_label.setGeometry(QtCore.QRect(18, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y_label.setFont(font)

        self.done_button = QtWidgets.QPushButton(self.tab)
        self.done_button.setGeometry(QtCore.QRect(270, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.done_button.setFont(font)
        self.done_button.setStyleSheet("background-color: rgb(96, 220, 137);")

        self.y_text_edit = QtWidgets.QPlainTextEdit(self.tab)
        self.y_text_edit.setGeometry(QtCore.QRect(195, 46, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y_text_edit.setFont(font)
        self.y_text_edit.setStyleSheet("background-color: white")

        self.x_text_edit = QtWidgets.QPlainTextEdit(self.tab)
        self.x_text_edit.setGeometry(QtCore.QRect(195, 8, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x_text_edit.setFont(font)
        self.x_text_edit.setStyleSheet("background-color: white")

        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()

        self.velocity_label_2 = QtWidgets.QLabel(self.tab_2)
        self.velocity_label_2.setGeometry(QtCore.QRect(18, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.velocity_label_2.setFont(font)

        self.angle_label = QtWidgets.QLabel(self.tab_2)
        self.angle_label.setGeometry(QtCore.QRect(18, 50, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angle_label.setFont(font)

        self.done_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.done_button_2.setGeometry(QtCore.QRect(270, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.done_button_2.setFont(font)
        self.done_button_2.setStyleSheet("background-color: rgb(96, 220, 137);")

        self.angle_text_edit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.angle_text_edit.setGeometry(QtCore.QRect(195, 46, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angle_text_edit.setFont(font)
        self.angle_text_edit.setStyleSheet("background-color: white")

        self.velocity_text_edit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.velocity_text_edit.setGeometry(QtCore.QRect(195, 8, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.velocity_text_edit.setFont(font)
        self.velocity_text_edit.setStyleSheet("background-color: white")

        self.angle_image = QtWidgets.QLabel(self.tab_2)
        self.angle_image.setGeometry(QtCore.QRect(80, 20, 91, 51))
        self.angle_image.setText("")
        self.angle_image.setPixmap(QtGui.QPixmap("../../Images/Simulator/Angle.png"))
        self.angle_image.setScaledContents(True)

        self.tabWidget.addTab(self.tab_2, "")

        self.radius_label = QtWidgets.QLabel(self.centralwidget)
        self.radius_label.setGeometry(QtCore.QRect(30, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radius_label.setFont(font)

        self.add_object_label = QtWidgets.QLabel(self.centralwidget)
        self.add_object_label.setGeometry(QtCore.QRect(10, 20, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.add_object_label.setFont(font)
        self.add_object_label.setAlignment(QtCore.Qt.AlignCenter)

        self.mass_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mass_text_edit.setGeometry(QtCore.QRect(115, 98, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mass_text_edit.setFont(font)
        self.mass_text_edit.setStyleSheet("background-color: white")

        self.radius_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.radius_text_edit.setGeometry(QtCore.QRect(115, 136, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radius_text_edit.setFont(font)
        self.radius_text_edit.setStyleSheet("background-color: white")

        self.elasticity_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.elasticity_text_edit.setGeometry(QtCore.QRect(306, 98, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.elasticity_text_edit.setFont(font)
        self.elasticity_text_edit.setStyleSheet("background-color: white")

        self.elasticity_label = QtWidgets.QLabel(self.centralwidget)
        self.elasticity_label.setGeometry(QtCore.QRect(222, 99, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.elasticity_label.setFont(font)

        self.friction_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.friction_text_edit.setGeometry(QtCore.QRect(306, 136, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.friction_text_edit.setFont(font)
        self.friction_text_edit.setStyleSheet("background-color: white")

        self.friction_label = QtWidgets.QLabel(self.centralwidget)
        self.friction_label.setGeometry(QtCore.QRect(222, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.friction_label.setFont(font)

        AddObject.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddObject)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddObject)

    def retranslateUi(self, AddObject):
        _translate = QtCore.QCoreApplication.translate
        AddObject.setWindowTitle(_translate("AddObject", "MainWindow"))
        self.mass_label.setText(_translate("AddObject", "Mass:"))
        self.velocity_label.setText(_translate("AddObject", "Velocity:"))
        self.x_label.setText(_translate("AddObject", "Horizontal:"))
        self.y_label.setText(_translate("AddObject", "Vertical:"))
        self.done_button.setText(_translate("AddObject", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AddObject", "Tab 1"))
        self.velocity_label_2.setText(_translate("AddObject", "Velocity:"))
        self.angle_label.setText(_translate("AddObject", "Angle:"))
        self.done_button_2.setText(_translate("AddObject", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AddObject", "Tab 2"))
        self.radius_label.setText(_translate("AddObject", "Radius:"))
        self.add_object_label.setText(_translate("AddObject", "Add [Object]"))
        self.elasticity_label.setText(_translate("AddObject", "Elasticity:"))
        self.friction_label.setText(_translate("AddObject", "Friction:"))
