# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/AddObject.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddObject(object):
    def setupUi(self, AddObject):
        AddObject.setObjectName("AddObject")
        AddObject.resize(467, 368)
        AddObject.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(AddObject)
        self.centralwidget.setObjectName("centralwidget")

        self.MassLabel = QtWidgets.QLabel(self.centralwidget)
        self.MassLabel.setGeometry(QtCore.QRect(30, 90, 51, 21))

        font = QtGui.QFont()
        font.setPointSize(14)

        self.MassLabel.setFont(font)
        self.MassLabel.setObjectName("MassLabel")

        self.VelocityLabel = QtWidgets.QLabel(self.centralwidget)
        self.VelocityLabel.setGeometry(QtCore.QRect(30, 196, 71, 21))

        font = QtGui.QFont()
        font.setPointSize(14)

        self.VelocityLabel.setFont(font)
        self.VelocityLabel.setObjectName("VelocityLabel")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 236, 401, 111))
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.xLabel = QtWidgets.QLabel(self.tab)
        self.xLabel.setGeometry(QtCore.QRect(18, 20, 101, 21))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.xLabel.setFont(font)
        self.xLabel.setObjectName("xLabel")

        self.xSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.xSpinBox.setGeometry(QtCore.QRect(190, 20, 50, 22))
        self.xSpinBox.setStyleSheet("background-color: white")
        self.xSpinBox.setObjectName("xSpinBox")

        self.ySpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.ySpinBox.setGeometry(QtCore.QRect(190, 50, 50, 22))
        self.ySpinBox.setStyleSheet("background-color: white")
        self.ySpinBox.setObjectName("ySpinBox")

        self.yLabel = QtWidgets.QLabel(self.tab)
        self.yLabel.setGeometry(QtCore.QRect(18, 50, 101, 21))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.yLabel.setFont(font)
        self.yLabel.setObjectName("yLabel")

        self.DoneButton = QtWidgets.QPushButton(self.tab)
        self.DoneButton.setGeometry(QtCore.QRect(270, 20, 101, 31))

        font = QtGui.QFont()
        font.setPointSize(14)

        self.DoneButton.setFont(font)
        self.DoneButton.setStyleSheet("background-color: rgb(96, 220, 137);")
        self.DoneButton.setObjectName("DoneButton")

        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.AngleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.AngleSpinBox.setGeometry(QtCore.QRect(190, 50, 50, 22))
        self.AngleSpinBox.setStyleSheet("background-color: white")
        self.AngleSpinBox.setObjectName("AngleSpinBox")

        self.VelocitySpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.VelocitySpinBox.setGeometry(QtCore.QRect(190, 20, 50, 22))
        self.VelocitySpinBox.setStyleSheet("background-color: white")
        self.VelocitySpinBox.setObjectName("VelocitySpinBox")

        self.VelocityLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.VelocityLabel_2.setGeometry(QtCore.QRect(18, 20, 151, 21))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.VelocityLabel_2.setFont(font)
        self.VelocityLabel_2.setObjectName("VelocityLabel_2")

        self.AngleLabel = QtWidgets.QLabel(self.tab_2)
        self.AngleLabel.setGeometry(QtCore.QRect(18, 50, 151, 21))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.AngleLabel.setFont(font)
        self.AngleLabel.setObjectName("AngleLabel")

        self.DoneButton2 = QtWidgets.QPushButton(self.tab_2)
        self.DoneButton2.setGeometry(QtCore.QRect(270, 20, 101, 31))

        font = QtGui.QFont()
        font.setPointSize(14)

        self.DoneButton2.setFont(font)
        self.DoneButton2.setStyleSheet("background-color: rgb(96, 220, 137);")
        self.DoneButton2.setObjectName("DoneButton2")

        self.tabWidget.addTab(self.tab_2, "")

        self.MassSpinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.MassSpinbox.setGeometry(QtCore.QRect(130, 90, 50, 22))
        self.MassSpinbox.setStyleSheet("background-color: white")
        self.MassSpinbox.setObjectName("MassSpinbox")

        self.RadiusLabel = QtWidgets.QLabel(self.centralwidget)
        self.RadiusLabel.setGeometry(QtCore.QRect(30, 125, 71, 21))

        font = QtGui.QFont()
        font.setPointSize(14)

        self.RadiusLabel.setFont(font)
        self.RadiusLabel.setObjectName("RadiusLabel")

        self.ColourLabel = QtWidgets.QLabel(self.centralwidget)
        self.ColourLabel.setGeometry(QtCore.QRect(30, 160, 71, 21))

        font = QtGui.QFont()
        font.setPointSize(14)

        self.ColourLabel.setFont(font)
        self.ColourLabel.setObjectName("ColourLabel")

        self.AddObjectLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddObjectLabel.setGeometry(QtCore.QRect(10, 20, 451, 51))

        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)

        self.AddObjectLabel.setFont(font)
        self.AddObjectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AddObjectLabel.setObjectName("AddObjectLabel")

        self.ColourComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ColourComboBox.setGeometry(QtCore.QRect(130, 160, 69, 22))
        self.ColourComboBox.setStyleSheet("background-color: white")
        self.ColourComboBox.setObjectName("ColourComboBox")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")
        self.ColourComboBox.addItem("")

        self.RadiusSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.RadiusSpinBox.setGeometry(QtCore.QRect(130, 125, 50, 22))
        self.RadiusSpinBox.setStyleSheet("background-color: white")
        self.RadiusSpinBox.setObjectName("RadiusSpinBox")

        AddObject.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddObject)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddObject)

    def retranslateUi(self, AddObject):
        _translate = QtCore.QCoreApplication.translate
        AddObject.setWindowTitle(_translate("AddObject", "MainWindow"))
        self.MassLabel.setText(_translate("AddObject", "Mass:"))
        self.VelocityLabel.setText(_translate("AddObject", "Velocity:"))
        self.xLabel.setText(_translate("AddObject", "Horizontal:"))
        self.yLabel.setText(_translate("AddObject", "Vertical:"))
        self.DoneButton.setText(_translate("AddObject", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AddObject", "Tab 1"))
        self.VelocityLabel_2.setText(_translate("AddObject", "Velocity:"))
        self.AngleLabel.setText(_translate("AddObject", "Angle from positive:"))
        self.DoneButton2.setText(_translate("AddObject", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AddObject", "Tab 2"))
        self.RadiusLabel.setText(_translate("AddObject", "Radius:"))
        self.ColourLabel.setText(_translate("AddObject", "Colour:"))
        self.AddObjectLabel.setText(_translate("AddObject", "Add [Object]"))
        self.ColourComboBox.setItemText(0, _translate("AddObject", "Red"))
        self.ColourComboBox.setItemText(1, _translate("AddObject", "Blue"))
        self.ColourComboBox.setItemText(2, _translate("AddObject", "Green"))
        self.ColourComboBox.setItemText(3, _translate("AddObject", "Orange"))
        self.ColourComboBox.setItemText(4, _translate("AddObject", "Yellow"))
        self.ColourComboBox.setItemText(5, _translate("AddObject", "Purple"))
        self.ColourComboBox.setItemText(6, _translate("AddObject", "Pink"))
        self.ColourComboBox.setItemText(7, _translate("AddObject", "Brown"))
        self.ColourComboBox.setItemText(8, _translate("AddObject", "Grey"))
        self.ColourComboBox.setItemText(9, _translate("AddObject", "White"))
        self.ColourComboBox.setItemText(10, _translate("AddObject", "Black"))
