# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/ApplyForce.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 174)
        MainWindow.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(13, 50, 401, 111))
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.x_label = QtWidgets.QLabel(self.tab)
        self.x_label.setGeometry(QtCore.QRect(18, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")

        self.y_label = QtWidgets.QLabel(self.tab)
        self.y_label.setGeometry(QtCore.QRect(18, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")

        self.done_button = QtWidgets.QPushButton(self.tab)
        self.done_button.setGeometry(QtCore.QRect(270, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.done_button.setFont(font)
        self.done_button.setStyleSheet("background-color: rgb(96, 220, 137);")
        self.done_button.setObjectName("done_button")

        self.y_text_edit = QtWidgets.QPlainTextEdit(self.tab)
        self.y_text_edit.setGeometry(QtCore.QRect(195, 46, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y_text_edit.setFont(font)
        self.y_text_edit.setStyleSheet("background-color: white")
        self.y_text_edit.setObjectName("y_text_edit")

        self.x_text_edit = QtWidgets.QPlainTextEdit(self.tab)
        self.x_text_edit.setGeometry(QtCore.QRect(195, 8, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x_text_edit.setFont(font)
        self.x_text_edit.setStyleSheet("background-color: white")
        self.x_text_edit.setObjectName("x_text_edit")

        self.positive_direction_image = QtWidgets.QLabel(self.tab)
        self.positive_direction_image.setGeometry(QtCore.QRect(110, 20, 71, 71))
        self.positive_direction_image.setText("")
        self.positive_direction_image.setPixmap(QtGui.QPixmap("../../Images/Simulator/Positive direction.png"))
        self.positive_direction_image.setScaledContents(True)
        self.positive_direction_image.setObjectName("positive_direction_image")

        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.velocity_label_2 = QtWidgets.QLabel(self.tab_2)
        self.velocity_label_2.setGeometry(QtCore.QRect(18, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.velocity_label_2.setFont(font)
        self.velocity_label_2.setObjectName("velocity_label_2")

        self.angle_label = QtWidgets.QLabel(self.tab_2)
        self.angle_label.setGeometry(QtCore.QRect(18, 50, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angle_label.setFont(font)
        self.angle_label.setObjectName("angle_label")

        self.done_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.done_button_2.setGeometry(QtCore.QRect(270, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.done_button_2.setFont(font)
        self.done_button_2.setStyleSheet("background-color: rgb(96, 220, 137);")
        self.done_button_2.setObjectName("done_button_2")

        self.angle_text_edit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.angle_text_edit.setGeometry(QtCore.QRect(195, 46, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.angle_text_edit.setFont(font)
        self.angle_text_edit.setStyleSheet("background-color: white")
        self.angle_text_edit.setObjectName("angle_text_edit")

        self.velocity_text_edit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.velocity_text_edit.setGeometry(QtCore.QRect(195, 8, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.velocity_text_edit.setFont(font)
        self.velocity_text_edit.setStyleSheet("background-color: white")
        self.velocity_text_edit.setObjectName("velocity_text_edit")

        self.angle_image = QtWidgets.QLabel(self.tab_2)
        self.angle_image.setGeometry(QtCore.QRect(80, 20, 91, 51))
        self.angle_image.setText("")
        self.angle_image.setPixmap(QtGui.QPixmap("../../Images/Simulator/Angle.png"))
        self.angle_image.setScaledContents(True)
        self.angle_image.setObjectName("angle_image")

        self.tabWidget.addTab(self.tab_2, "")

        self.apply_force_label = QtWidgets.QLabel(self.centralwidget)
        self.apply_force_label.setGeometry(QtCore.QRect(10, 18, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.apply_force_label.setFont(font)
        self.apply_force_label.setAlignment(QtCore.Qt.AlignCenter)
        self.apply_force_label.setObjectName("apply_force_label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.x_label.setText(_translate("MainWindow", "Horizontal:"))
        self.y_label.setText(_translate("MainWindow", "Vertical:"))
        self.done_button.setText(_translate("MainWindow", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.velocity_label_2.setText(_translate("MainWindow", "Velocity:"))
        self.angle_label.setText(_translate("MainWindow", "Angle:"))
        self.done_button_2.setText(_translate("MainWindow", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.apply_force_label.setText(_translate("MainWindow", "Apply force"))
