# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/ChooseQuestionInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 212)
        MainWindow.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.model_label = QtWidgets.QLabel(self.centralwidget)
        self.model_label.setGeometry(QtCore.QRect(40, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.model_label.setFont(font)
        self.model_label.setObjectName("model_label")

        self.difficulty_level_label = QtWidgets.QLabel(self.centralwidget)
        self.difficulty_level_label.setGeometry(QtCore.QRect(40, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.difficulty_level_label.setFont(font)
        self.difficulty_level_label.setObjectName("difficulty_level_label")

        self.question_button = QtWidgets.QPushButton(self.centralwidget)
        self.question_button.setGeometry(QtCore.QRect(140, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.question_button.setFont(font)
        self.question_button.setStyleSheet("background-color: #ffffff")
        self.question_button.setObjectName("question_button")

        self.difficulty_level_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.difficulty_level_combobox.setGeometry(QtCore.QRect(220, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.difficulty_level_combobox.setFont(font)
        self.difficulty_level_combobox.setStyleSheet("background-color: #ffffff")
        self.difficulty_level_combobox.setObjectName("difficulty_level_combobox")
        self.difficulty_level_combobox.addItem("")
        self.difficulty_level_combobox.addItem("")
        self.difficulty_level_combobox.addItem("")

        self.model_selected_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.model_selected_combobox.setGeometry(QtCore.QRect(220, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.model_selected_combobox.setFont(font)
        self.model_selected_combobox.setStyleSheet("background-color: #ffffff")
        self.model_selected_combobox.setObjectName("model_selected_combobox")
        self.model_selected_combobox.addItem("")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.model_label.setText(_translate("MainWindow", "Model:"))
        self.difficulty_level_label.setText(_translate("MainWindow", "Difficulty level:"))
        self.question_button.setText(_translate("MainWindow", "Add a question"))
        self.difficulty_level_combobox.setItemText(0, _translate("MainWindow", "Easy"))
        self.difficulty_level_combobox.setItemText(1, _translate("MainWindow", "Intermediate"))
        self.difficulty_level_combobox.setItemText(2, _translate("MainWindow", "Difficult"))
        self.model_selected_combobox.setItemText(0, _translate("MainWindow", "New Item"))
