# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/GraphDataInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 212)
        MainWindow.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.object_selected_label = QtWidgets.QLabel(self.centralwidget)
        self.object_selected_label.setGeometry(QtCore.QRect(40, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.object_selected_label.setFont(font)
        self.object_selected_label.setObjectName("object_selected_label")

        self.variable_label = QtWidgets.QLabel(self.centralwidget)
        self.variable_label.setGeometry(QtCore.QRect(40, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.variable_label.setFont(font)
        self.variable_label.setObjectName("variable_label")

        self.plot_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_button.setGeometry(QtCore.QRect(230, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plot_button.setFont(font)
        self.plot_button.setStyleSheet("background-color: #ffffff")
        self.plot_button.setObjectName("plot_button")

        self.variable_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.variable_combobox.setGeometry(QtCore.QRect(220, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.variable_combobox.setFont(font)
        self.variable_combobox.setStyleSheet("background-color: #ffffff")
        self.variable_combobox.setObjectName("variable_combobox")
        self.variable_combobox.addItem("")

        self.object_selected_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.object_selected_combobox.setGeometry(QtCore.QRect(220, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.object_selected_combobox.setFont(font)
        self.object_selected_combobox.setStyleSheet("background-color: #ffffff")
        self.object_selected_combobox.setObjectName("object_selected_combobox")
        self.object_selected_combobox.addItem("")

        self.update_object_list_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_object_list_button.setGeometry(QtCore.QRect(60, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.update_object_list_button.setFont(font)
        self.update_object_list_button.setStyleSheet("background-color: #ffffff")
        self.update_object_list_button.setObjectName("update_object_list_button")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.object_selected_label.setText(_translate("MainWindow", "Object selected:"))
        self.variable_label.setText(_translate("MainWindow", "Variable to plot:"))
        self.plot_button.setText(_translate("MainWindow", "Plot graph"))
        self.variable_combobox.setItemText(0, _translate("MainWindow", "New Item"))
        self.object_selected_combobox.setItemText(0, _translate("MainWindow", "New Item"))
        self.update_object_list_button.setText(_translate("MainWindow", "Update object list"))
