# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/MessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 80)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 261, 31))
        self.frame.setStyleSheet("background-color: black")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.MessageLabel = QtWidgets.QLabel(self.frame)
        self.MessageLabel.setGeometry(QtCore.QRect(0, 0, 261, 31))

        font = QtGui.QFont()
        font.setPointSize(11)

        self.MessageLabel.setFont(font)
        self.MessageLabel.setStyleSheet("color: white")
        self.MessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MessageLabel.setObjectName("MessageLabel")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MessageLabel.setText(_translate("MainWindow", "Choose position of object"))
