# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/ModelInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 145)
        MainWindow.setStyleSheet("background-color: #d1dbe3")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.model_label = QtWidgets.QLabel(self.centralwidget)
        self.model_label.setGeometry(QtCore.QRect(50, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.model_label.setFont(font)

        self.add_model_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_model_button.setGeometry(QtCore.QRect(220, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_model_button.setFont(font)
        self.add_model_button.setStyleSheet("background-color: #ffffff")

        self.model_text_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.model_text_edit.setGeometry(QtCore.QRect(190, 20, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.model_text_edit.setFont(font)
        self.model_text_edit.setStyleSheet("background-color: #ffffff")

        self.invalid_label = QtWidgets.QLabel(self.centralwidget)
        self.invalid_label.setGeometry(QtCore.QRect(60, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.invalid_label.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.model_label.setText(_translate("MainWindow", "Model:"))
        self.add_model_button.setText(_translate("MainWindow", "Add model"))
        self.invalid_label.setText(_translate("MainWindow", "Input valid model"))
