# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/ObjectsTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 200)
        Form.setStyleSheet("background-color: #b4cede")

        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 710, 130))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 708, 128))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.object_button1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.object_button1.setStyleSheet("background-color: #d1dbe3")
        self.object_button1.setObjectName("object_button1")

        self.horizontalLayout_2.addWidget(self.object_button1)

        self.object_button2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.object_button2.setStyleSheet("background-color: #d1dbe3")
        self.object_button2.setObjectName("object_button2")

        self.horizontalLayout_2.addWidget(self.object_button2)

        self.object_button3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.object_button3.setStyleSheet("background-color: #d1dbe3")
        self.object_button3.setObjectName("object_button3")

        self.horizontalLayout_2.addWidget(self.object_button3)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 10, 710, 130))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")

        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setEnabled(True)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 708, 128))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.model1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.model1.setStyleSheet("background-color: #d1dbe3")
        self.model1.setObjectName("model1")

        self.horizontalLayout_3.addWidget(self.model1)

        self.model2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.model2.setStyleSheet("background-color: #d1dbe3")
        self.model2.setObjectName("model2")

        self.horizontalLayout_3.addWidget(self.model2)

        self.model3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.model3.setStyleSheet("background-color: #d1dbe3")
        self.model3.setObjectName("model3")

        self.horizontalLayout_3.addWidget(self.model3)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.tabWidget.addTab(self.tab_2, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.object_button1.setText(_translate("Form", "Circle"))
        self.object_button2.setText(_translate("Form", "Rectangle"))
        self.object_button3.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.model1.setText(_translate("Form", "Cannon"))
        self.model2.setText(_translate("Form", "PushButton"))
        self.model3.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
