# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/ProjectileInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 297)
        MainWindow.setStyleSheet("background-color: #d1dbe3")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.confirm_button_box = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.confirm_button_box.setGeometry(QtCore.QRect(90, 230, 151, 61))
        self.confirm_button_box.setStyleSheet("background-color: #ffffff")
        self.confirm_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirm_button_box.setObjectName("confirm_button_box")

        self.angle_label = QtWidgets.QLabel(self.centralwidget)
        self.angle_label.setGeometry(QtCore.QRect(20, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.angle_label.setFont(font)
        self.angle_label.setObjectName("angle_label")
        self.angle_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.angle_text_edit.setGeometry(QtCore.QRect(200, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.angle_text_edit.setFont(font)
        self.angle_text_edit.setStyleSheet("background-color: #ffffff")
        self.angle_text_edit.setObjectName("angle_text_edit")
        self.invalid_label = QtWidgets.QLabel(self.centralwidget)
        self.invalid_label.setGeometry(QtCore.QRect(50, 220, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.invalid_label.setFont(font)
        self.invalid_label.setStyleSheet("")
        self.invalid_label.setObjectName("invalid_label")
        self.initial_velocity_label = QtWidgets.QLabel(self.centralwidget)
        self.initial_velocity_label.setGeometry(QtCore.QRect(20, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.initial_velocity_label.setFont(font)
        self.initial_velocity_label.setObjectName("initial_velocity_label")
        self.initial_velocity_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.initial_velocity_text_edit.setGeometry(QtCore.QRect(200, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.initial_velocity_text_edit.setFont(font)
        self.initial_velocity_text_edit.setStyleSheet("background-color: #ffffff")
        self.initial_velocity_text_edit.setObjectName("initial_velocity_text_edit")
        self.positive_direction_image = QtWidgets.QLabel(self.centralwidget)
        self.positive_direction_image.setGeometry(QtCore.QRect(60, 100, 111, 110))
        self.positive_direction_image.setText("")
        self.positive_direction_image.setPixmap(QtGui.QPixmap("UI/Qt\\../../Images/Simulator/Positive direction for cannon.png"))
        self.positive_direction_image.setObjectName("positive_direction_image")
        self.angle_direction_image = QtWidgets.QLabel(self.centralwidget)
        self.angle_direction_image.setGeometry(QtCore.QRect(170, 100, 81, 61))
        self.angle_direction_image.setText("")
        self.angle_direction_image.setPixmap(QtGui.QPixmap("UI/Qt\\../../Images/Simulator/Angle.png"))
        self.angle_direction_image.setScaledContents(True)
        self.angle_direction_image.setObjectName("angle_direction_image")
        self.initial_velocity_label.raise_()
        self.confirm_button_box.raise_()
        self.angle_label.raise_()
        self.angle_text_edit.raise_()
        self.initial_velocity_text_edit.raise_()
        self.positive_direction_image.raise_()
        self.angle_direction_image.raise_()
        self.invalid_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.angle_label.setText(_translate("MainWindow", "Angle in degrees:"))
        self.invalid_label.setText(_translate("MainWindow", "Input valid"))
        self.initial_velocity_label.setText(_translate("MainWindow", "Initial velocity:"))
