# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/QuestionInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 212)
        MainWindow.setStyleSheet("background-color: #d1dbe3")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question_label = QtWidgets.QLabel(self.centralwidget)
        self.question_label.setGeometry(QtCore.QRect(50, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.question_label.setFont(font)
        self.question_label.setObjectName("question_label")
        self.add_question_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_question_button.setGeometry(QtCore.QRect(410, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_question_button.setFont(font)
        self.add_question_button.setStyleSheet("background-color: #ffffff")
        self.add_question_button.setObjectName("add_question_button")
        self.question_text_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.question_text_edit.setGeometry(QtCore.QRect(190, 20, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.question_text_edit.setFont(font)
        self.question_text_edit.setStyleSheet("background-color: #ffffff")
        self.question_text_edit.setObjectName("question_text_edit")
        self.answer_text_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_text_edit.setGeometry(QtCore.QRect(190, 70, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.answer_text_edit.setFont(font)
        self.answer_text_edit.setStyleSheet("background-color: #ffffff")
        self.answer_text_edit.setObjectName("answer_text_edit")
        self.answer_label = QtWidgets.QLabel(self.centralwidget)
        self.answer_label.setGeometry(QtCore.QRect(50, 70, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.answer_label.setFont(font)
        self.answer_label.setObjectName("answer_label")

        self.invalid_label = QtWidgets.QLabel(self.centralwidget)
        self.invalid_label.setGeometry(QtCore.QRect(90, 140, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.invalid_label.setFont(font)
        self.invalid_label.setObjectName("invalid_label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.question_label.setText(_translate("MainWindow", "Question:"))
        self.add_question_button.setText(_translate("MainWindow", "Add question"))
        self.answer_label.setText(_translate("MainWindow", "Answer:"))
        self.invalid_label.setText(_translate("MainWindow", "Input valid questions and answers"))
