# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/SaveProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 194)
        MainWindow.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.save_button_box = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.save_button_box.setGeometry(QtCore.QRect(90, 120, 151, 61))
        self.save_button_box.setStyleSheet("background-color: #ffffff")
        self.save_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.save_button_box.setObjectName("save_button_box")

        self.save_label = QtWidgets.QLabel(self.centralwidget)
        self.save_label.setGeometry(QtCore.QRect(30, 20, 241, 31))

        font = QtGui.QFont()
        font.setPointSize(16)

        self.save_label.setFont(font)
        self.save_label.setObjectName("save_label")

        self.project_name_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.project_name_text_edit.setGeometry(QtCore.QRect(50, 70, 231, 31))

        font = QtGui.QFont()
        font.setPointSize(11)

        self.project_name_text_edit.setFont(font)
        self.project_name_text_edit.setStyleSheet("background-color: #ffffff")
        self.project_name_text_edit.setObjectName("project_name_text_edit")

        self.invalid_label = QtWidgets.QLabel(self.centralwidget)
        self.invalid_label.setGeometry(QtCore.QRect(55, 105, 121, 16))

        font = QtGui.QFont()
        font.setPointSize(11)

        self.invalid_label.setFont(font)
        self.invalid_label.setStyleSheet("")
        self.invalid_label.setObjectName("invalid_label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save_label.setText(_translate("MainWindow", "Save project as:"))
        self.invalid_label.setText(_translate("MainWindow", "Input valid name"))
