# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/SavedProjects.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrebuiltModelsPage(object):
    def setupUi(self, PrebuiltModelsPage):

        PrebuiltModelsPage.setObjectName("PrebuiltModelsPage")
        PrebuiltModelsPage.resize(1600, 900)
        PrebuiltModelsPage.setMinimumSize(QtCore.QSize(1600, 900))

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 206, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 206, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 206, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 206, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PrebuiltModelsPage.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget(PrebuiltModelsPage)
        self.centralwidget.setObjectName("centralwidget")

        self.project_list = QtWidgets.QListWidget(self.centralwidget)
        self.project_list.setGeometry(QtCore.QRect(400, 280, 811, 301))

        font = QtGui.QFont()
        font.setPointSize(26)

        self.project_list.setFont(font)
        self.project_list.setObjectName("project_list")

        item = QtWidgets.QListWidgetItem()
        self.project_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_list.addItem(item)

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 90, 1601, 141))

        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)

        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")

        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(75, 50, 75, 75))
        self.back_button.setStyleSheet("")
        self.back_button.setText("")

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Images/BackButtonIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.back_button.setIcon(icon)
        self.back_button.setIconSize(QtCore.QSize(60, 60))
        self.back_button.setObjectName("back_button")

        PrebuiltModelsPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(PrebuiltModelsPage)
        QtCore.QMetaObject.connectSlotsByName(PrebuiltModelsPage)

    def retranslateUi(self, PrebuiltModelsPage):
        _translate = QtCore.QCoreApplication.translate
        PrebuiltModelsPage.setWindowTitle(_translate("PrebuiltModelsPage", "MainWindow"))
        __sortingEnabled = self.project_list.isSortingEnabled()
        self.project_list.setSortingEnabled(False)
        item = self.project_list.item(0)
        item.setText(_translate("PrebuiltModelsPage", "Projectile Motion"))
        item = self.project_list.item(1)
        item.setText(_translate("PrebuiltModelsPage", "Circular Motion"))
        item = self.project_list.item(2)
        item.setText(_translate("PrebuiltModelsPage", "Inclined Planes"))
        item = self.project_list.item(3)
        item.setText(_translate("PrebuiltModelsPage", "Simple harmonic motion"))
        item = self.project_list.item(4)
        item.setText(_translate("PrebuiltModelsPage", "Momentum"))
        item = self.project_list.item(5)
        item.setText(_translate("PrebuiltModelsPage", "Moments"))
        self.project_list.setSortingEnabled(__sortingEnabled)
        self.title.setText(_translate("PrebuiltModelsPage", "SavedProjects"))
