# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/SceneObjectProperties.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 572)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(21, 19, 275, 151))
        self.groupBox.setStyleSheet("background-color:#7bb2e3")

        self.scene_properties_label = QtWidgets.QLabel(self.groupBox)
        self.scene_properties_label.setGeometry(QtCore.QRect(0, -1, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.scene_properties_label.setFont(font)
        self.scene_properties_label.setAlignment(QtCore.Qt.AlignCenter)

        self.gravitational_acceleration_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.gravitational_acceleration_spinbox.setGeometry(QtCore.QRect(200, 43, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gravitational_acceleration_spinbox.setFont(font)
        self.gravitational_acceleration_spinbox.setStyleSheet("background-color: #d1dbe3")

        self.gravitational_acceleration_label = QtWidgets.QLabel(self.groupBox)
        self.gravitational_acceleration_label.setGeometry(QtCore.QRect(10, 43, 191, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gravitational_acceleration_label.setFont(font)

        self.choose_planet_gravitational_acceleration_label = QtWidgets.QLabel(self.groupBox)
        self.choose_planet_gravitational_acceleration_label.setGeometry(QtCore.QRect(10, 68, 221, 16))

        self.earth_gravitational_acceleration_button = QtWidgets.QPushButton(self.groupBox)
        self.earth_gravitational_acceleration_button.setGeometry(QtCore.QRect(22, 94, 51, 31))
        self.earth_gravitational_acceleration_button.setStyleSheet("background-color: rgb(96, 220, 137);")

        self.moon_gravitational_acceleration_button = QtWidgets.QPushButton(self.groupBox)
        self.moon_gravitational_acceleration_button.setGeometry(QtCore.QRect(82, 94, 51, 31))
        self.moon_gravitational_acceleration_button.setStyleSheet("background-color: white")

        self.mars_gravitational_acceleration_button = QtWidgets.QPushButton(self.groupBox)
        self.mars_gravitational_acceleration_button.setGeometry(QtCore.QRect(142, 94, 51, 31))
        self.mars_gravitational_acceleration_button.setStyleSheet("background-color: white")

        self.jupiter_gravitational_acceleration_button = QtWidgets.QPushButton(self.groupBox)
        self.jupiter_gravitational_acceleration_button.setGeometry(QtCore.QRect(202, 94, 51, 31))
        self.jupiter_gravitational_acceleration_button.setStyleSheet("background-color: white")

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(21, 171, 275, 381))
        self.groupBox_2.setStyleSheet("background-color:#7bb2e3")

        self.object_properties_label = QtWidgets.QLabel(self.groupBox_2)
        self.object_properties_label.setGeometry(QtCore.QRect(0, -1, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.object_properties_label.setFont(font)
        self.object_properties_label.setAlignment(QtCore.Qt.AlignCenter)

        self.mass_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.mass_spinbox.setGeometry(QtCore.QRect(200, 250, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mass_spinbox.setFont(font)
        self.mass_spinbox.setStyleSheet("background-color: #d1dbe3")

        self.mass_label = QtWidgets.QLabel(self.groupBox_2)
        self.mass_label.setGeometry(QtCore.QRect(19, 252, 161, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mass_label.setFont(font)

        self.object_selected_label = QtWidgets.QLabel(self.groupBox_2)
        self.object_selected_label.setGeometry(QtCore.QRect(19, 50, 161, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.object_selected_label.setFont(font)

        self.object_selected_combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.object_selected_combobox.setGeometry(QtCore.QRect(160, 49, 101, 22))
        self.object_selected_combobox.setStyleSheet("background-color: #d1dbe3")

        self.friction_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.friction_spinbox.setEnabled(True)
        self.friction_spinbox.setGeometry(QtCore.QRect(200, 310, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friction_spinbox.setFont(font)
        self.friction_spinbox.setStyleSheet("background-color: #d1dbe3")

        self.elasticity_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.elasticity_spinbox.setEnabled(True)
        self.elasticity_spinbox.setGeometry(QtCore.QRect(200, 280, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elasticity_spinbox.setFont(font)
        self.elasticity_spinbox.setStyleSheet("background-color: #d1dbe3")

        self.velocity_vectors_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.velocity_vectors_checkbox.setGeometry(QtCore.QRect(19, 114, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.velocity_vectors_checkbox.setFont(font)

        self.elasticity_label = QtWidgets.QLabel(self.groupBox_2)
        self.elasticity_label.setGeometry(QtCore.QRect(20, 282, 161, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.elasticity_label.setFont(font)

        self.friction_label = QtWidgets.QLabel(self.groupBox_2)
        self.friction_label.setGeometry(QtCore.QRect(20, 314, 161, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.friction_label.setFont(font)

        self.update_list_button = QtWidgets.QPushButton(self.groupBox_2)
        self.update_list_button.setGeometry(QtCore.QRect(20, 80, 111, 23))
        self.update_list_button.setStyleSheet("background-color:rgb(111, 212, 255)")

        self.delete_object_button = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_object_button.setGeometry(QtCore.QRect(30, 340, 221, 23))
        self.delete_object_button.setStyleSheet("background-color:rgb(255, 40, 40)")

        self.confirm_edits_button = QtWidgets.QPushButton(self.groupBox_2)
        self.confirm_edits_button.setGeometry(QtCore.QRect(145, 80, 110, 23))
        self.confirm_edits_button.setStyleSheet("background-color:rgb(111, 212, 255)")

        self.force_vectors_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.force_vectors_checkbox.setGeometry(QtCore.QRect(20, 145, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.force_vectors_checkbox.setFont(font)

        self.apply_force_button = QtWidgets.QPushButton(self.groupBox_2)
        self.apply_force_button.setGeometry(QtCore.QRect(40, 179, 201, 23))
        self.apply_force_button.setStyleSheet("background-color:rgb(111, 212, 255)")

        self.remove_all_forces_button = QtWidgets.QPushButton(self.groupBox_2)
        self.remove_all_forces_button.setGeometry(QtCore.QRect(40, 211, 201, 23))
        self.remove_all_forces_button.setStyleSheet("background-color:rgb(111, 212, 255)")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.scene_properties_label.setText(_translate("MainWindow", "Scene properties"))
        self.gravitational_acceleration_label.setText(_translate("MainWindow", "Gravitational acceleration:"))
        self.choose_planet_gravitational_acceleration_label.setText(_translate("MainWindow", "Choose gravitational acceleration of planets:"))
        self.earth_gravitational_acceleration_button.setText(_translate("MainWindow", "Earth"))
        self.moon_gravitational_acceleration_button.setText(_translate("MainWindow", "Moon"))
        self.mars_gravitational_acceleration_button.setText(_translate("MainWindow", "Mars"))
        self.jupiter_gravitational_acceleration_button.setText(_translate("MainWindow", "Jupiter"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.object_properties_label.setText(_translate("MainWindow", "Object properties"))
        self.mass_label.setText(_translate("MainWindow", "Mass"))
        self.object_selected_label.setText(_translate("MainWindow", "Object selected:"))
        self.velocity_vectors_checkbox.setText(_translate("MainWindow", "Velocity vectors"))
        self.elasticity_label.setText(_translate("MainWindow", "Elasticity"))
        self.friction_label.setText(_translate("MainWindow", "Friction"))
        self.update_list_button.setText(_translate("MainWindow", "Update list"))
        self.delete_object_button.setText(_translate("MainWindow", "Delete object"))
        self.confirm_edits_button.setText(_translate("MainWindow", "Confirm edits"))
        self.force_vectors_checkbox.setText(_translate("MainWindow", "Force vectors"))
        self.apply_force_button.setText(_translate("MainWindow", "Apply force"))
        self.remove_all_forces_button.setText(_translate("MainWindow", "Remove all forces"))
