# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(501, 433)
        Settings.setAutoFillBackground(False)
        Settings.setStyleSheet("background-color: #d1dbe3")

        self.centralwidget = QtWidgets.QWidget(Settings)

        self.settings_title = QtWidgets.QLabel(self.centralwidget)
        self.settings_title.setGeometry(QtCore.QRect(0, 10, 521, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.settings_title.setFont(font)
        self.settings_title.setStyleSheet("background-color; gray")
        self.settings_title.setAlignment(QtCore.Qt.AlignCenter)

        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(50, 90, 400, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_widget.setFont(font)

        self.tab = QtWidgets.QWidget()

        self.dark_mode_checkbox = QtWidgets.QCheckBox(self.tab)
        self.dark_mode_checkbox.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dark_mode_checkbox.setFont(font)

        self.time_step_slider = QtWidgets.QSlider(self.tab)
        self.time_step_slider.setGeometry(QtCore.QRect(40, 150, 281, 22))
        self.time_step_slider.setOrientation(QtCore.Qt.Horizontal)

        self.time_step_label = QtWidgets.QLabel(self.tab)
        self.time_step_label.setGeometry(QtCore.QRect(20, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_step_label.setFont(font)

        self.show_grid_checkbox = QtWidgets.QCheckBox(self.tab)
        self.show_grid_checkbox.setGeometry(QtCore.QRect(20, 55, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.show_grid_checkbox.setFont(font)

        self.default_time_step_button = QtWidgets.QPushButton(self.tab)
        self.default_time_step_button.setGeometry(QtCore.QRect(20, 190, 121, 23))

        self.tab_widget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()

        self.delete_stats_button = QtWidgets.QPushButton(self.tab_2)
        self.delete_stats_button.setGeometry(QtCore.QRect(70, 227, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delete_stats_button.setFont(font)
        self.delete_stats_button.setStyleSheet("background-color:rgb(255, 40, 40)")

        self.stats_label = QtWidgets.QLabel(self.tab_2)
        self.stats_label.setGeometry(QtCore.QRect(20, 20, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stats_label.setFont(font)

        self.questions_answered_label = QtWidgets.QLabel(self.tab_2)
        self.questions_answered_label.setGeometry(QtCore.QRect(40, 60, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.questions_answered_label.setFont(font)

        self.accuracy_label = QtWidgets.QLabel(self.tab_2)
        self.accuracy_label.setGeometry(QtCore.QRect(40, 120, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accuracy_label.setFont(font)

        self.correct_answers_label = QtWidgets.QLabel(self.tab_2)
        self.correct_answers_label.setGeometry(QtCore.QRect(40, 90, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.correct_answers_label.setFont(font)

        self.tab_widget.addTab(self.tab_2, "")

        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "MainWindow"))
        self.settings_title.setText(_translate("Settings", "Settings"))
        self.dark_mode_checkbox.setText(_translate("Settings", "Dark mode"))
        self.time_step_label.setText(_translate("Settings", "Time step: 0.1"))
        self.show_grid_checkbox.setText(_translate("Settings", "Show grid"))
        self.default_time_step_button.setText(_translate("Settings", "Default time step"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("Settings", "Tab 1"))
        self.delete_stats_button.setText(_translate("Settings", "Delete statistics"))
        self.stats_label.setText(_translate("Settings", "Interactive mode question statistics:"))
        self.questions_answered_label.setText(_translate("Settings", "Questions answered: "))
        self.accuracy_label.setText(_translate("Settings", "Accuracy: "))
        self.correct_answers_label.setText(_translate("Settings", "Correct answers: "))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("Settings", "Tab 2"))
