# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Qt/InteractiveMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 212)
        MainWindow.setStyleSheet("background-color: #d1dbe3")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 20, 1101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.question_label = QtWidgets.QLabel(self.centralwidget)
        self.question_label.setGeometry(QtCore.QRect(0, 60, 1101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.question_label.setFont(font)
        self.question_label.setAlignment(QtCore.Qt.AlignCenter)
        self.question_label.setObjectName("question_label")
        self.answer_text_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_text_edit.setGeometry(QtCore.QRect(410, 107, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.answer_text_edit.setFont(font)
        self.answer_text_edit.setStyleSheet("background-color: #ffffff")
        self.answer_text_edit.setObjectName("answer_text_edit")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(454, 164, 91, 23))
        self.submit_button.setStyleSheet("background-color: #ffffff")
        self.submit_button.setObjectName("submit_button")
        self.skip_button = QtWidgets.QPushButton(self.centralwidget)
        self.skip_button.setGeometry(QtCore.QRect(559, 164, 91, 23))
        self.skip_button.setStyleSheet("background-color: #ffffff")
        self.skip_button.setObjectName("skip_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Projectile Questions"))
        self.question_label.setText(_translate("MainWindow", "If the projectile is launched with a velocity of 50 m/s, with an angle of 30 to the positive horizontal, what would the vertical velocity component be in m/s?"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.skip_button.setText(_translate("MainWindow", "Skip"))
